Improve configuration instructions for 2.7.x
alibaba/jetcache pull request #709
Opened 2022-08-30 16:19 UTC by dylan-tao

YAML Config更直观展示更多2.7.x的特性，完善2.7+和2.6-版本keyConvert和ValueConvert配置说明

2022-08-30 16:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/jetcache?pullRequest=709) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/jetcache?pullRequest=709) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/jetcache?pullRequest=709) it.</sub>

2022-08-31 04:40 UTC, areyouok requested changes

2022-08-31 04:40 UTC, areyouok commented on docs/CN/Config.md
> +      keyConvertor: fastjson/fastjson2/jackson
这样不好吧，这无法解析了，可以把其它可选用注释标明出来。

2022-08-31 04:40 UTC, areyouok commented on docs/CN/Config.md
> +| jetcache.[local/remote].${area}.keyConvertor | 无(2.6-)<br/>fastjson2(2.7+) | key转换器的全局配置，2.7+已经支持的keyConvertor：```fastjson2```/```jackson```；<br/>2.6-只有一个已经实现的keyConvertor：```fastjson```。仅当使用@Creat
这里默认值直接写fastjson2好了，2.6的后期版本也是有默认值的（fastjson），另外jackson作为keyconvertor在2.6的后期版本也是支持的。

2022-08-31 06:08 UTC, dylan-tao commented on docs/CN/Config.md
> +      keyConvertor: fastjson/fastjson2/jackson
done

2022-08-31 06:08 UTC, dylan-tao commented on docs/CN/Config.md
> +| jetcache.[local/remote].${area}.keyConvertor | 无(2.6-)<br/>fastjson2(2.7+) | key转换器的全局配置，2.7+已经支持的keyConvertor：```fastjson2```/```jackson```；<br/>2.6-只有一个已经实现的keyConvertor：```fastjson```。仅当使用@Creat
done

2022-08-31 08:43 UTC, areyouok requested changes

2022-08-31 08:43 UTC, areyouok commented on docs/CN/Config.md
> +      valueEncoder: java #其他可选：fastjson2/jackson/kryo4/kryo5
"kryo4" -> "kryo"，这个要保持和以前的兼容

2022-08-31 08:51 UTC, dylan-tao commented on docs/CN/Config.md
> +      valueEncoder: java #其他可选：fastjson2/jackson/kryo4/kryo5
done. Last update. Give you some encouragement and support.

2022-08-31 08:52 UTC, merged