the home page exploits the 2.7.x feature
alibaba/jetcache pull request #711
Opened 2022-08-31 09:39 UTC by dylan-tao

the home page exploits the 2.7.x feature

2022-08-31 09:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/jetcache?pullRequest=711) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/jetcache?pullRequest=711) before we can accept your contribution.<br/><hr/>**taodizhou** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/jetcache?pullRequest=711) it.</sub>

2022-08-31 10:07 UTC, areyouok commented on readme.MD
> +      valueDecoder: java #other choose：fastjson2/jackson/kryo/kryo5
突然想起来，json类的encoder/decoder，包括fastjson2和jackson，默认是没有注册的，这里设置了也不能用，文档里面还是不要提了。如果谁要用，就自己搞定。

2022-08-31 13:40 UTC, dylan-tao commented on readme.MD
> +      valueDecoder: java #other choose：fastjson2/jackson/kryo/kryo5
好了

2022-09-01 01:40 UTC, areyouok requested changes

2022-09-01 01:40 UTC, areyouok commented on readme.MD
> +* Cache key convertor supported: ```fastjson2```/```jackson```; Value convertor supported: ```java```/```kryo```/```kryo5```
keyconvertor 这里还少个fastjson

2022-10-08 16:07 UTC, dylan-tao commented on readme.MD
> +* Cache key convertor supported: ```fastjson2```/```jackson```; Value convertor supported: ```java```/```kryo```/```kryo5```
DONE

2022-10-08 16:07 UTC, dylan-tao commented on readme.MD
> +* Cache key convertor supported: ```fastjson2```/```jackson```; Value convertor supported: ```java```/```kryo```/```kryo5```
> keyconvertor 这里还少个fastjson
> 
> Keyconvertor is missing fastjson

DONE

2022-11-12 01:56 UTC, merged