synchronized to lock
alibaba/jetcache pull request #820
Opened 2023-09-29 03:47 UTC by zt9788

兼容JDK21的虚拟线程

2023-09-29 12:12 UTC, areyouok commented
有个单测没过，你再看看

2023-09-29 14:12 UTC, zt9788 commented
> 有个单测没过，你再看看
冲突了,改了一下,现在应该可以了,你在看看

2023-09-29 14:23 UTC, areyouok commented
明天我再看下

2023-09-29 14:24 UTC, zt9788 commented
> 明天我再看下

不急,中秋快乐

2023-09-30 03:41 UTC, areyouok requested changes

2023-09-30 03:41 UTC, areyouok commented on jetcache-starter/jetcache-autoconfigure/src/main/java/com/alicp/jetcache/autoconfigure/AbstractCacheAutoInit.java
> +    private final static ReentrantLock reentrantLock = new ReentrantLock();
这里好像不用static？

2023-09-30 03:41 UTC, areyouok commented on jetcache-core/src/main/java/com/alicp/jetcache/WeakHashReentrantLock.java
> +public class WeakHashReentrantLock {
这个类我可能没完全看懂，按我现在的理解，它是多余的，不用这么复杂

2023-09-30 03:41 UTC, areyouok commented on jetcache-core/src/main/java/com/alicp/jetcache/embedded/AbstractEmbeddedCache.java
> +            Lock lock = weakLock.reentrantLock(holder);
我理解你是为了这个地方引入了WeakHashReentrantLock。这个地方以前是在holder上加锁，是一个细粒度锁，但锁内执行的代码没有会导致堵塞的io操作，所以可以直接改为粗粒度锁，加一个ReentrantLock作为AbstractEmbeddedCache类的成员变量即可，不会有什么性能影响。

2023-09-30 03:41 UTC, areyouok commented on jetcache-core/src/main/java/com/alicp/jetcache/AbstractCache.java
> +    protected final ReentrantLock reentrantLock = new ReentrantLock();
这里可以改成static

2023-09-30 03:41 UTC, areyouok commented on jetcache-core/src/main/java/com/alicp/jetcache/embedded/LinkedHashMapCache.java
> +        public LRUMap(int max, Object lockObj) {
以前的代码，这个构造函数的第二个参数，是多余的。这里直接添加一个Lock作为LRUMap的成员变量就行了。

2023-09-30 06:05 UTC, zt9788 commented on jetcache-core/src/main/java/com/alicp/jetcache/WeakHashReentrantLock.java
> +public class WeakHashReentrantLock {
对,这个主要为了解决LinkedHashMapCache细颗粒度锁的问题.如果其他几个地方不需要,那只保留读写锁部分应该就可以了

2023-09-30 06:06 UTC, zt9788 commented on jetcache-core/src/main/java/com/alicp/jetcache/embedded/AbstractEmbeddedCache.java
> +            Lock lock = weakLock.reentrantLock(holder);
好的,我晚一点修改一下,在提交上次,其他问题同

2023-09-30 06:26 UTC, areyouok commented on jetcache-core/src/main/java/com/alicp/jetcache/embedded/AbstractEmbeddedCache.java
> +            Lock lock = weakLock.reentrantLock(holder);
继续添加commit就行，已经解决的地方你可以标记为解决。

2023-09-30 12:21 UTC, areyouok requested changes

2023-09-30 12:21 UTC, areyouok commented on jetcache-core/src/main/java/com/alicp/jetcache/embedded/LinkedHashMapCache.java
> +        public LRUMap(int max, Object lockObj) {
lockObj这个参数没有用了，应该删除掉。

2023-09-30 12:21 UTC, areyouok commented on jetcache-core/src/main/java/com/alicp/jetcache/support/JetCacheExecutor.java
> +    protected static final ReentrantLock reentrantLock = new ReentrantLock();
这个地方private就行了。我忘记上面两行为什么是protected了，为了保持兼容性上面两行可以不改（尽管应该不会有人用）。

2023-09-30 12:22 UTC, areyouok commented
问题不大了，增加了一些小的修改要求。

2023-09-30 14:40 UTC, zt9788 commented on jetcache-core/src/main/java/com/alicp/jetcache/support/JetCacheExecutor.java
> +    protected static final ReentrantLock reentrantLock = new ReentrantLock();
明天我改一下

2023-10-01 03:08 UTC, merged