feat: support jedis cluster pipeline
alibaba/jetcache pull request #866
Opened 2024-03-21 06:49 UTC by Roiocam

## References

#865

2024-03-21 06:50 UTC, Roiocam commented on jetcache-support/jetcache-redis/src/main/java/com/alicp/jetcache/redis/RedisCache.java
> +                throw new UnsupportedOperationException("unrecognized pipeline type");
不会有到达 else 的情况，升级到 5.x 会有一个 AbstractPipelineBase

2024-03-21 13:45 UTC, Roiocam commented on jetcache-starter/jetcache-autoconfigure/src/main/java/com/alicp/jetcache/autoconfigure/RedisAutoConfiguration.java
> +                    return new JedisClusterWrapper(hostAndPortSet, connectionTimeout, soTimeout, maxAttempt, user, password,
不升级 Jedis，但是我们也拿不到 ClusterConnectionProvider，我能想到对原有代码结构改动最小的方案就是通过一个 Wrapper 来实现了

2024-03-21 14:25 UTC, Roiocam commented
试了一下，单测在我本地运行没啥问题, 重开 PR 试一试：

<img width="859" alt="截屏2024-03-21 22 25 23" src="https://github.com/alibaba/jetcache/assets/26020358/c89cae13-3ad4-4f18-9550-a3a2ecbd0e3a">

2024-03-21 16:56 UTC, Roiocam commented
Tada, CI passed! solve my previous deadlock commit.

2024-03-26 14:54 UTC, areyouok requested changes

2024-03-26 14:54 UTC, areyouok commented on jetcache-support/jetcache-redis/src/main/java/com/alicp/jetcache/redis/RedisCache.java
> +            // JedisPooled, JedisCluster 都是用到连接池的连接，需要还回去
不要留中文注释

2024-03-26 14:54 UTC, areyouok commented on jetcache-support/jetcache-redis/src/main/java/com/alicp/jetcache/redis/RedisCacheConfig.java
> +    public ClusterConnectionProvider getProvider() {
这些修改我还是建议做到RedisCache类里面。因为这是内部实现，写在这里，这个config类多出一个用户会看见的public方法，但实际上他们不需要用。而且这破坏了config类的简单性

2024-03-27 02:11 UTC, Roiocam commented on jetcache-support/jetcache-redis/src/main/java/com/alicp/jetcache/redis/RedisCache.java
> +            // JedisPooled, JedisCluster 都是用到连接池的连接，需要还回去
Fixed

2024-03-27 03:14 UTC, merged