feat: improve the performance of jedis batch commands.
alibaba/jetcache pull request #873
Opened 2024-03-28 07:25 UTC by Roiocam

See: https://github.com/alibaba/jetcache/issues/865#issuecomment-2024561604

抽象了一下 pipeline 获取的接口，方便其他方法使用（getAll, delAll）

2024-03-28 10:16 UTC, areyouok requested changes

2024-03-28 10:16 UTC, areyouok commented on jetcache-support/jetcache-redis/src/main/java/com/alicp/jetcache/redis/RedisCache.java
> +            return biFunction.apply(pipeline, null);
这样不太对，biFuction丢出异常，然后又调用它自己处理，调用了两次，感觉怪怪的。

2024-03-28 10:16 UTC, areyouok commented on jetcache-support/jetcache-redis/src/main/java/com/alicp/jetcache/redis/RedisCache.java
> +                // Which is faster between pipeline.get or Jedis.mget()?
我猜直接mget性能更好，不过需要测试。我觉得如果能用mget就直接调用mget就行了。以前的JedisCluster不能用mget，所以单独处理了，现在我看已经可以直接调用mget了。

2024-03-28 10:30 UTC, areyouok commented
redis cluster是不是不能很好的支持mget/mset？

2024-03-28 10:35 UTC, Roiocam commented on jetcache-support/jetcache-redis/src/main/java/com/alicp/jetcache/redis/RedisCache.java
> +                // Which is faster between pipeline.get or Jedis.mget()?
这个注释忘记去掉了，代码是直接调用 mget 的

2024-03-28 10:49 UTC, Roiocam commented
> redis cluster是不是不能很好的支持mget/mset？

这个不清楚，但是 JedisCluster 这个对象是没有的，他的 mget 就是创建了一个：CommandObject, 里面有个 CommandArguments 

最后在 ClusterCommandExecutor 里面执行的：

https://github.com/redis/jedis/blob/a02b2eb2dcb1c9ff31afe3fa91ebdd3fad8cad7e/src/main/java/redis/clients/jedis/executors/ClusterCommandExecutor.java#L90-L92

然后拿连接也是根据命令参数算出来 slot：

https://github.com/redis/jedis/blob/a02b2eb2dcb1c9ff31afe3fa91ebdd3fad8cad7e/src/main/java/redis/clients/jedis/providers/ClusterConnectionProvider.java#L100-L103

Key 在不同的 SLOT 的时候，Redis Cluster 自身就会拒绝这个请求的：

https://github.com/redis/redis/blob/0b34396924eca4edc524469886dc5be6c77ec4ed/src/cluster.c#L1068-L1076


我试了一下，JedisCluster 也确实体现了这一点：

```
        ClusterCommandObjects clusterCommandObjects = new ClusterCommandObjects();
        CommandObject<List<String>> mget = clusterCommandObjects.mget("a", "b", "c", "d");
        System.out.println("mget");

Exception in thread "main" redis.clients.jedis.exceptions.JedisClusterOperationException: Keys must belong to same hashslot.

```

2024-03-28 10:51 UTC, Roiocam commented on jetcache-support/jetcache-redis/src/main/java/com/alicp/jetcache/redis/RedisCache.java
> +            return biFunction.apply(pipeline, null);
我晚些时候看看怎么改

2024-03-29 01:33 UTC, Roiocam commented on jetcache-support/jetcache-redis/src/main/java/com/alicp/jetcache/redis/RedisCache.java
> +            return biFunction.apply(pipeline, null);
用两个函数表示的话，阅读起来可能不太美观，这里的 biFunction 想用类似于 CompletableFuture 的 handle 来用.

新改的 API 还是用 handle 处理返回的结果，中间加了个可以用于请求的 Function

2024-03-29 05:17 UTC, areyouok requested changes

2024-03-29 05:17 UTC, areyouok commented on jetcache-support/jetcache-redis/src/main/java/com/alicp/jetcache/redis/RedisCache.java
> +            return biFunction.apply(result, null);
这样还是有biFuction丢出的一场biFunction自己来处理的问题。这样传两个函数太绕了，直接在do _GET_ALL等方法里面try catch就行了吧。

2024-03-29 05:44 UTC, Roiocam commented on jetcache-support/jetcache-redis/src/main/java/com/alicp/jetcache/redis/RedisCache.java
> +            return biFunction.apply(result, null);
是的，如果设计上不打算让 biFunction 抛出异常就没问题，只处理 (res,ex)，这样可能清晰点，返回在一处，try catch 感觉代码太长就拆开了，不过可能是我自己习惯问题，我改回来，不用 biFunction 处理吧

2024-03-29 08:56 UTC, areyouok requested changes

2024-03-29 08:56 UTC, areyouok commented on jetcache-support/jetcache-redis/src/main/java/com/alicp/jetcache/redis/RedisCache.java
> +        StringBinaryCommands readCommands = (StringBinaryCommands) readCommands();
这一行也应该放到try catch里面，下同

2024-03-29 08:56 UTC, areyouok commented on jetcache-support/jetcache-redis/src/main/java/com/alicp/jetcache/redis/RedisCache.java
> +        AtomicLong x = new AtomicLong();
这里不要用AtomicLong吧，哪怕用long[]呢，CAS毕竟还是有开销的

2024-03-29 08:56 UTC, areyouok commented on jetcache-support/jetcache-redis/src/main/java/com/alicp/jetcache/redis/RedisCache.java
> +            } else if (commands instanceof JedisPooled && pipelineFirst) {
pipelineFirst写前面，可以短路instanceof判断

2024-03-29 09:31 UTC, Roiocam commented on jetcache-support/jetcache-redis/src/main/java/com/alicp/jetcache/redis/RedisCache.java
> +            } else if (commands instanceof JedisPooled && pipelineFirst) {
fixed

2024-03-29 09:44 UTC, merged