fix: expiration time did not expect environment #915
alibaba/jetcache pull request #916
Opened 2024-08-22 08:46 UTC by Roiocam

2024-08-23 04:59 UTC, areyouok requested changes

2024-08-23 06:41 UTC, Roiocam commented on jetcache-core/src/main/java/com/alicp/jetcache/MultiLevelCache.java
>                  r = cache.PUT(key, value);
那这样的话，如果用户主动 PUT 一个大于配置时间的过期时间，就不行了。这个 PR 我想到一些边界，还没测试

2024-08-23 07:58 UTC, areyouok commented on jetcache-core/src/main/java/com/alicp/jetcache/MultiLevelCache.java
>                  r = cache.PUT(key, value);
"用户主动 PUT 一个大于配置时间的过期时间"，那样的话timeUnit应该不是null

2024-09-04 11:47 UTC, areyouok commented on jetcache-core/src/main/java/com/alicp/jetcache/MultiLevelCache.java
>                  r = cache.PUT(key, value);
你说的这个问题存在，怎么又改回去了呢

2024-10-28 15:18 UTC, areyouok commented
这个还改吗？

2026-04-30 06:47 UTC, Roiocam commented
> 这个还改吗？

done

2026-05-19 13:36 UTC, areyouok commented
这个我看了好久，还是不合适。useExpireOfSubCache做成了3态，但是好像没有地方设置。

此外，之前的useExpireOfSubCache还是有必要的，local/remote集中在同一个时间点过期，高负载下不是好事。

我自己做了个commit，应该实现了你的需求。完全保持兼容，新增了一个全局开关：

https://github.com/alibaba/jetcache/commit/965b35bd7e53193dec2b9029f75b7fd90012a1d0

2026-05-19 13:36 UTC, closed without merging